name: "Setup Deno with cache"
description: "Composite action wrapper around denoland/setup-deno and actions/cache to setup Deno and cache its dependencies."
branding:
  icon: fast-forward
  color: gray-dark

inputs:
  deno-version:
    description: "The Deno version to install. Can be a semver version of a stable release, 'canary' for the latest canary, or the Git hash of a specific canary release."
    default: "1.x"
  deno-json-path:
    description: "The path to the Deno config file to use for caching. Defaults to an empty string, using the built-in CLI default."
    default: ""
  deno-lock-path:
    description: "The path to the lock file to use for caching. Defaults to `./deno.lock`."
    default: "./deno.lock"
  directory:
    description: "The path to the scripts to cache. Defaults to the repo root."
    default: "."

outputs:
  deno-version:
    description: "The Deno version that was installed."
    value: ${{ steps.setup-deno.outputs.deno-version }}
  is-canary:
    description: "If the installed Deno version was a canary version."
    value: ${{ steps.setup-deno.outputs.is-canary }}
  cache-hit:
    description: "A boolean value to indicate an exact match was found for the key."
    value: ${{ steps.cache-deno.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Setup Deno
      id: setup-deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ inputs.deno-version }}
      
    - name: Set Deno cache dir
      shell: bash
      run: echo "DENO_DIR=${{ runner.os == 'Windows' && 'C:\\deno_cache' || '/tmp/deno_cache' }}" >> $GITHUB_ENV

    - name: Cache Deno dependencies
      id: cache-deno
      uses: actions/cache@v3
      with:
        key: ${{ hashFiles(inputs.deno-lock-path) }}
        path: ${{ env.DENO_DIR }}

    - name: Restore Deno dependencies
      shell: bash
      run: |
        find ${{ runner.os == 'macOS' && '-E' || '' }} \
          ${{ inputs.directory }} \
          -regex '.+\.[tj]sx?$' \
          -exec deno cache {} ${{ inputs.deno-json-path != '' && '--config=' || '' }}${{ inputs.deno-json-path }} \;