name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Deno
        uses: ./

      - run: deno run -A ./bundle.ts

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "dist/*"
          commit_message: "chore: build action bundle"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
