name: Test

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  basic:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Basic on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: ./
        with:
          deno-config-path: "test/basic/deno.json"

      - name: Test basic usage
        run: deno run -A ./test/basic/main.ts
